[build]
  command = "npm run build"
  publish = "employwise-frontend/build"

[context.production.environment]
  NODE_VERSION = "18"

[context.deploy-preview]
  command = "npm run build"
  publish = "employwise-frontend/build"
